JULIA:=julia
MAIN:=src/main.jl

REDBENCH_NUM_THREADS?=1
export OMP_NUM_THREADS:=$(REDBENCH_NUM_THREADS)
export JULIA_NUM_THREADS:=$(REDBENCH_NUM_THREADS)

run:
	$(JULIA) -t $(JULIA_NUM_THREADS) $(MAIN)


